# Spring Boot应用配置
spring:
  application:
    name: SpringBoot-HouseMarket # 应用名称，用于服务注册和发现
  datasource:
    # 数据库连接URL，包含MySQL特定参数
    url: jdbc:mysql://localhost:3306/housemarket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 日志编码配置
  output:
    ansi:
      enabled: always
  mvc:
    async:
      request-timeout: 30s
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  cache:
    type: simple

app:
  outbox:
    poll-interval: 2000
    reset-interval: 60000
upload:
  dir: ./uploads

# SpringDoc Swagger配置
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    defaultModelsExpandDepth: -1

logging:
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:DnYFooRaZqdDXLi6GZQ4210ksbgDV3PTZQGa35OZNXJQIt6hGankli3gt6/cT6fP}
